// Generated by commsdsl2comms v3.3.1

#pragma once

#include <memory>
#include <QtCore/QVariantList>
#include "comms_champion/ProtocolMessageBase.h"
#include "mqtt311/message/Connack.h"
#include "cc_plugin/Message.h"

namespace mqtt311
{

namespace cc_plugin
{

namespace message
{

class Connack : public
    comms_champion::ProtocolMessageBase<
        mqtt311::message::Connack<mqtt311::cc_plugin::Message>,
        Connack
    >
{
public:
    Connack();
    Connack(const Connack&) = delete;
    Connack(Connack&&) = delete;
    virtual ~Connack();
    Connack& operator=(const Connack&);
    Connack& operator=(Connack&&);

protected:
    virtual const QVariantList& fieldsPropertiesImpl() const override;
};

} // namespace message

} // namespace cc_plugin

} // namespace mqtt311



