// Generated by commsdsl2comms v3.5.1

#pragma once

#include <memory>
#include <QtCore/QVariantList>
#include "comms_champion/ProtocolMessageBase.h"
#include "mqtt311/message/Pingreq.h"
#include "cc_plugin/Message.h"

namespace mqtt311
{

namespace cc_plugin
{

namespace message
{

class Pingreq : public
    comms_champion::ProtocolMessageBase<
        mqtt311::message::Pingreq<mqtt311::cc_plugin::Message>,
        Pingreq
    >
{
public:
    Pingreq();
    Pingreq(const Pingreq&) = delete;
    Pingreq(Pingreq&&) = delete;
    virtual ~Pingreq();
    Pingreq& operator=(const Pingreq&);
    Pingreq& operator=(Pingreq&&);

protected:
    virtual const QVariantList& fieldsPropertiesImpl() const override;
};

} // namespace message

} // namespace cc_plugin

} // namespace mqtt311



