// Generated by commsdsl2comms v5.2.0

/// @file
/// @brief Contains definition of the ClientInputMessages messages bundle.

#pragma once

#include <tuple>
#include "cc_mqtt311/message/Connack.h"
#include "cc_mqtt311/message/Pingresp.h"
#include "cc_mqtt311/message/Puback.h"
#include "cc_mqtt311/message/Pubcomp.h"
#include "cc_mqtt311/message/Publish.h"
#include "cc_mqtt311/message/Pubrec.h"
#include "cc_mqtt311/message/Pubrel.h"
#include "cc_mqtt311/message/Suback.h"
#include "cc_mqtt311/message/Unsuback.h"
#include "cc_mqtt311/options/DefaultOptions.h"

namespace cc_mqtt311
{

namespace input
{

/// @brief Messages of the protocol in ascending order.
/// @tparam TBase Base class of all the messages.
/// @tparam TOpt Protocol definition options.
template <typename TBase, typename TOpt = cc_mqtt311::options::DefaultOptions>
using ClientInputMessages =
    std::tuple<
        cc_mqtt311::message::Connack<TBase, TOpt>,
        cc_mqtt311::message::Publish<TBase, TOpt>,
        cc_mqtt311::message::Puback<TBase, TOpt>,
        cc_mqtt311::message::Pubrec<TBase, TOpt>,
        cc_mqtt311::message::Pubrel<TBase, TOpt>,
        cc_mqtt311::message::Pubcomp<TBase, TOpt>,
        cc_mqtt311::message::Suback<TBase, TOpt>,
        cc_mqtt311::message::Unsuback<TBase, TOpt>,
        cc_mqtt311::message::Pingresp<TBase, TOpt>
    >;

} // namespace input

} // namespace cc_mqtt311
