// Generated by commsdsl2comms v7.1.0

/// @file
/// @brief Contains common template parameters independent functionality of
///    @ref cc_mqtt311::field::BinData field.

#pragma once

namespace cc_mqtt311
{

namespace field
{

/// @brief Common types and functions for
///     @ref cc_mqtt311::field::BinData field.
struct BinDataCommon
{
    /// @brief Name of the @ref cc_mqtt311::field::BinData field.
    static const char* name()
    {
        return "BinData";
    }
};

} // namespace field

} // namespace cc_mqtt311
