// Generated by commsdsl2comms v6.3.3

/// @file
/// @brief Contains common template parameters independent functionality of
///    @ref cc_mqtt311::field::ProtocolName field.

#pragma once

namespace cc_mqtt311
{

namespace field
{

/// @brief Common types and functions for
///     @ref cc_mqtt311::field::ProtocolName field.
struct ProtocolNameCommon
{
    /// @brief Name of the @ref cc_mqtt311::field::ProtocolName field.
    static const char* name()
    {
        return "Protocol Name";
    }
};

} // namespace field

} // namespace cc_mqtt311
