// Generated by commsdsl2comms v5.1.3

/// @file
/// @brief Contains common template parameters independent functionality of
///    @ref cc_mqtt311::field::String field.

#pragma once

namespace cc_mqtt311
{

namespace field
{

/// @brief Common types and functions for
///     @ref cc_mqtt311::field::String field.
struct StringCommon
{
    /// @brief Name of the @ref cc_mqtt311::field::String field.
    static const char* name()
    {
        return "String";
    }
};

} // namespace field

} // namespace cc_mqtt311
