// Generated by commsdsl2comms v8.0.0

/// @file
/// @brief Contains message factory with dynamic memory allocation for the server input messages.

#pragma once

#include <cstdint>
#include <memory>
#include "cc_mqtt311/input/ServerInputMessages.h"
#include "comms/MsgFactoryCreateFailureReason.h"

namespace cc_mqtt311
{

namespace factory
{

/// @brief Message factory with dynamic memory allocation for the server input messages.
/// @details Defines the same public interface as @b comms::MsgFactory and intended for
///     its replacement.
/// @tparam TInterface Interface class of the messages.
/// @tparam TProtOptions Application specific protocol definition options.
template<typename TInterface, typename TProtOptions>
class ServerInputMessagesDynMemMsgFactory
{
public:
    /// @brief Type of the common base class of all the messages.
    using Message = TInterface;

    /// @brief Type of the message ID when passed as a parameter.
    using MsgIdParamType = typename Message::MsgIdParamType;

    /// @brief Type of the message ID.
    using MsgIdType = typename Message::MsgIdType;

    /// @brief Smart pointer to @ref Message which holds allocated message object.
    using MsgPtr = std::unique_ptr<Message>;

    /// @brief Reason for message creation failure
    using CreateFailureReason = comms::MsgFactoryCreateFailureReason;

    /// @brief Type of generic message.
    /// @details Not supported
    using GenericMessage = void;

    /// @brief Create message object given the ID of the message.
    /// @param id ID of the message.
    /// @param idx Relative index (or offset) of the message with the same ID.
    /// @param[out] reason Failure reason in case creation has failed.
    MsgPtr createMsg(MsgIdParamType id, unsigned idx = 0U, CreateFailureReason* reason = nullptr) const
    {
        auto updateReasonFunc =
            [reason](CreateFailureReason val)
            {
                if (reason != nullptr) {
                    *reason = val;
                }
            };

        if (1U <= idx) {
            updateReasonFunc(CreateFailureReason::InvalidId);
            return MsgPtr();
        }

        updateReasonFunc(CreateFailureReason::None);
        switch (static_cast<std::intmax_t>(id)) {
            case 1 /* 0x1 */: return MsgPtr(new cc_mqtt311::message::Connect<TInterface, TProtOptions>);
            case 3 /* 0x3 */: return MsgPtr(new cc_mqtt311::message::Publish<TInterface, TProtOptions>);
            case 4 /* 0x4 */: return MsgPtr(new cc_mqtt311::message::Puback<TInterface, TProtOptions>);
            case 5 /* 0x5 */: return MsgPtr(new cc_mqtt311::message::Pubrec<TInterface, TProtOptions>);
            case 6 /* 0x6 */: return MsgPtr(new cc_mqtt311::message::Pubrel<TInterface, TProtOptions>);
            case 7 /* 0x7 */: return MsgPtr(new cc_mqtt311::message::Pubcomp<TInterface, TProtOptions>);
            case 8 /* 0x8 */: return MsgPtr(new cc_mqtt311::message::Subscribe<TInterface, TProtOptions>);
            case 10 /* 0xa */: return MsgPtr(new cc_mqtt311::message::Unsubscribe<TInterface, TProtOptions>);
            case 12 /* 0xc */: return MsgPtr(new cc_mqtt311::message::Pingreq<TInterface, TProtOptions>);
            case 14 /* 0xe */: return MsgPtr(new cc_mqtt311::message::Disconnect<TInterface, TProtOptions>);
            default: break;
        }

        updateReasonFunc(CreateFailureReason::InvalidId);
        return MsgPtr();
    }

    /// @brief Allocate and initialise @b comms::GenericMessage object.
    MsgPtr createGenericMsg(MsgIdParamType id, unsigned idx = 0U) const
    {
        static_cast<void>(id);
        static_cast<void>(idx);
        return MsgPtr();
    }

    /// @brief Inquiry whether allocation is possible
    bool canAllocate() const
    {
        return true;
    }

    /// @brief Get number of message types that have the specified ID.
    /// @param id ID of the message.
    /// @return Number of message classes that report same ID.
    std::size_t msgCount(MsgIdParamType id) const
    {
        switch (static_cast<std::intmax_t>(id))
        {
            case 1 /* 0x1 */: return 1;
            case 3 /* 0x3 */: return 1;
            case 4 /* 0x4 */: return 1;
            case 5 /* 0x5 */: return 1;
            case 6 /* 0x6 */: return 1;
            case 7 /* 0x7 */: return 1;
            case 8 /* 0x8 */: return 1;
            case 10 /* 0xa */: return 1;
            case 12 /* 0xc */: return 1;
            case 14 /* 0xe */: return 1;
            default: break;
        }

        return 0U;
    }

    /// @brief Compile time inquiry whether all the message classes have unique IDs.
    static constexpr bool hasUniqueIds()
    {
        return true;
    }

    /// @brief Compile time inquiry whether polymorphic dispatch tables are
    ///     generated internally to map message ID to actual type.
    static constexpr bool isDispatchPolymorphic()
    {
        return false;
    }

    /// @brief Compile time inquiry whether static binary search dispatch is
    ///     generated internally to map message ID to actual type.
    static constexpr bool isDispatchStaticBinSearch()
    {
        return false;
    }

    /// @brief Compile time inquiry whether linear switch dispatch is
    ///     generated internally to map message ID to actual type.
    static constexpr bool isDispatchLinearSwitch()
    {
        return false;
    }

    /// @brief Compile time inquiry whether factory supports in-place allocation
    static constexpr bool hasInPlaceAllocation()
    {
        return false;
    }

    /// @brief Compile time inquiry whether factory supports @b comms::GenericMessage allocation.
    static constexpr bool hasGenericMessageSupport()
    {
        return false;
    }

    /// @brief Compile time inquiry whether factory has forced dispatch method
    static constexpr bool hasForcedDispatch()
    {
        return true;
    }
};

} // namespace factory

} // namespace cc_mqtt311
