// Generated by commsdsl2comms v6.3.0

/// @file
/// @brief Contains common template parameters independent functionality of
///    @ref cc_mqtt311::message::Disconnect message and its fields.

#pragma once

namespace cc_mqtt311
{

namespace message
{

/// @brief Common types and functions of 
///     @ref cc_mqtt311::message::Disconnect message.
struct DisconnectCommon
{
    /// @brief Name of the @ref cc_mqtt311::message::Disconnect message.
    static const char* name()
    {
        return "DISCONNECT";
    }
};

} // namespace message

} // namespace cc_mqtt311
