// Generated by commsdsl2comms v5.1.3

/// @file
/// @brief Contains common template parameters independent functionality of
///    @ref cc_mqtt311::message::Pingresp message and its fields.

#pragma once

namespace cc_mqtt311
{

namespace message
{

/// @brief Common types and functions of 
///     @ref cc_mqtt311::message::Pingresp message.
struct PingrespCommon
{
    /// @brief Name of the @ref cc_mqtt311::message::Pingresp message.
    static const char* name()
    {
        return "PINGRESP";
    }
};

} // namespace message

} // namespace cc_mqtt311
