// Generated by commsdsl2comms v5.2.0

/// @file
/// @brief Contains common template parameters independent functionality of
///    @ref cc_mqtt311::message::Pingreq message and its fields.

#pragma once

namespace cc_mqtt311
{

namespace message
{

/// @brief Common types and functions of 
///     @ref cc_mqtt311::message::Pingreq message.
struct PingreqCommon
{
    /// @brief Name of the @ref cc_mqtt311::message::Pingreq message.
    static const char* name()
    {
        return "PINGREQ";
    }
};

} // namespace message

} // namespace cc_mqtt311
