// Generated by commsdsl2comms v6.3.3

/// @file
/// @brief Contains common template parameters independent functionality of
///    @ref cc_mqtt311::message::Unsuback message and its fields.

#pragma once

#include "cc_mqtt311/field/PacketIdCommon.h"

namespace cc_mqtt311
{

namespace message
{

/// @brief Common types and functions for fields of 
///     @ref cc_mqtt311::message::Unsuback message.
/// @see cc_mqtt311::message::UnsubackFields
struct UnsubackFieldsCommon
{
    /// @brief Common types and functions for
    ///     @ref cc_mqtt311::message::UnsubackFields::PacketId field.
    using PacketIdCommon = cc_mqtt311::field::PacketIdCommon;
};

/// @brief Common types and functions of 
///     @ref cc_mqtt311::message::Unsuback message.
struct UnsubackCommon
{
    /// @brief Name of the @ref cc_mqtt311::message::Unsuback message.
    static const char* name()
    {
        return "UNSUBACK";
    }
};

} // namespace message

} // namespace cc_mqtt311
