// Generated by commsdsl2comms v7.0.0

/// @file
/// @brief Contains definition of protocol data view default options.

#pragma once

#include "cc_mqtt311/options/DefaultOptions.h"

namespace cc_mqtt311
{

namespace options
{

/// @brief Default data view options of the protocol.
template <typename TBase = cc_mqtt311::options::DefaultOptions>
struct DataViewDefaultOptionsT : public TBase
{
    /// @brief Extra options for fields.
    struct field : public TBase::field
    {
        /// @brief Extra options for @ref
        ///     cc_mqtt311::field::BinData field.
        using BinData =
            std::tuple<
                comms::option::app::OrigDataView,
                typename TBase::field::BinData
            >;

        /// @brief Extra options for @ref
        ///     cc_mqtt311::field::String field.
        using String =
            std::tuple<
                comms::option::app::OrigDataView,
                typename TBase::field::String
            >;
    }; // struct field

    /// @brief Extra options for messages.
    struct message : public TBase::message
    {
        /// @brief Extra options for fields of
        ///     @ref cc_mqtt311::message::Connect message.
        struct ConnectFields : public TBase::message::ConnectFields
        {
            /// @brief Extra options for @ref
            ///     cc_mqtt311::message::ConnectFields::ProtocolName
            ///     field.
            using ProtocolName =
                std::tuple<
                    comms::option::app::OrigDataView,
                    typename TBase::message::ConnectFields::ProtocolName
                >;
        };

        /// @brief Extra options for fields of
        ///     @ref cc_mqtt311::message::Publish message.
        struct PublishFields : public TBase::message::PublishFields
        {
            /// @brief Extra options for @ref
            ///     cc_mqtt311::message::PublishFields::Payload
            ///     field.
            using Payload =
                std::tuple<
                    comms::option::app::OrigDataView,
                    typename TBase::message::PublishFields::Payload
                >;
        };
    }; // struct message

    /// @brief Extra options for frames.
    struct frame : public TBase::frame
    {
        /// @brief Extra options for layers of
        ///     @ref cc_mqtt311::frame::Frame frame.
        struct FrameLayers : public TBase::frame::FrameLayers
        {
            /// @brief Extra options for @ref
            ///     cc_mqtt311::frame::FrameLayers::DataMembers::Field field.
            struct DataMembers : public TBase::frame::FrameLayers::Data
            {
                using Field =
                    std::tuple<
                        comms::option::app::OrigDataView,
                        typename TBase::frame::FrameLayers::Data::Field
                    >;
            }; // struct DataMembers
        }; // struct FrameLayers
    }; // struct frame
};

/// @brief Alias to @ref DataViewDefaultOptionsT with default template parameter.
using DataViewDefaultOptions = DataViewDefaultOptionsT<>;

} // namespace options

} // namespace cc_mqtt311
