// Generated by commsdsl2comms v5.0.0

/// @file
/// @brief Contains common template parameters independent functionality of
///    @ref mqtt311::field::String field.

#pragma once

namespace mqtt311
{

namespace field
{

/// @brief Common types and functions for
///     @ref mqtt311::field::String field.
struct StringCommon
{
    /// @brief Name of the @ref mqtt311::field::String field.
    static const char* name()
    {
        return "String";
    }
};

} // namespace field

} // namespace mqtt311
