// Generated by commsdsl2comms v3.5.1

/// @file
/// @brief Contains common template parameters independent functionality of
///    @ref mqtt311::field::String field.

#pragma once

namespace mqtt311
{

namespace field
{

/// @brief Scope for all the common definitions of the
///     @ref mqtt311::field::String field.
struct StringCommon
{
    /// @brief Name of the @ref mqtt311::field::String field.
    static const char* name()
    {
        return "String";
    }
    
};


} // namespace field

} // namespace mqtt311


