// Generated by commsdsl2comms v3.7.0

/// @file
/// @brief Contains common template parameters independent functionality of
///    @ref mqtt311::message::Disconnect message and its fields.

#pragma once

namespace mqtt311
{

namespace message
{

/// @brief Common types and functions of 
///     @ref mqtt311::message::Disconnect message.
/// @see mqtt311::message::Disconnect
struct DisconnectCommon
{
    /// @brief Name of the @ref mqtt311::message::Disconnect message.
    static const char* name()
    {
        return "DISCONNECT";
    }
    
};

} // namespace message

} // namespace mqtt311


