// Generated by commsdsl2comms v3.5.0

/// @file
/// @brief Contains common template parameters independent functionality of
///    @ref mqtt311::message::Pingreq message and its fields.

#pragma once

namespace mqtt311
{

namespace message
{

/// @brief Common types and functions of 
///     @ref mqtt311::message::Pingreq message.
/// @see mqtt311::message::Pingreq
struct PingreqCommon
{
    /// @brief Name of the @ref mqtt311::message::Pingreq message.
    static const char* name()
    {
        return "PINGREQ";
    }
    
};

} // namespace message

} // namespace mqtt311


