// Generated by commsdsl2comms v3.3.2

/// @file
/// @brief Contains common template parameters independent functionality of
///    @ref mqtt311::message::Unsubscribe message and its fields.

#pragma once

#include "mqtt311/field/PacketIdCommon.h"
#include "mqtt311/field/TopicCommon.h"

namespace mqtt311
{

namespace message
{

/// @brief Common types and functions for fields of 
///     @ref mqtt311::message::Unsubscribe message.
/// @see mqtt311::message::UnsubscribeFields
struct UnsubscribeFieldsCommon
{
    /// @brief Common types and functions for
    ///     @ref mqtt311::message::UnsubscribeFields::PacketId field.
    using PacketIdCommon = mqtt311::field::PacketIdCommon;
    
    /// @brief Scope for all the common definitions of the member fields of
    ///     @ref mqtt311::message::UnsubscribeFields::List list.
    struct ListMembersCommon
    {
        /// @brief Common types and functions for
        ///     @ref mqtt311::message::UnsubscribeFields::ListMembers::Topic field.
        using TopicCommon = mqtt311::field::TopicCommon;
        
    };
    
    /// @brief Scope for all the common definitions of the
    ///     @ref mqtt311::message::UnsubscribeFields::List field.
    struct ListCommon
    {
        /// @brief Name of the @ref mqtt311::message::UnsubscribeFields::List field.
        static const char* name()
        {
            return "List";
        }
        
    };
    
    
};

/// @brief Common types and functions of 
///     @ref mqtt311::message::Unsubscribe message.
/// @see mqtt311::message::Unsubscribe
struct UnsubscribeCommon
{
    /// @brief Name of the @ref mqtt311::message::Unsubscribe message.
    static const char* name()
    {
        return "UNSUBSCRIBE";
    }
    
};

} // namespace message

} // namespace mqtt311


